[package]
name = "gui-framework"
version = "0.1.0"
authors = ["Robin Kock <robin@kock-hamburg.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
