use std::io::Cursor;

use glium::texture::{MipmapsOption, Texture2d};
use glium::{texture::RawImage2d, Display};

pub fn load_png_texture(display: &Display, bytes: &[u8]) -> Texture2d {
    let image = image::load(Cursor::new(bytes), image::ImageFormat::Png)
        .unwrap()
        .to_rgba8();
    let image_dimensions = image.dimensions();
    let image = RawImage2d::from_raw_rgba_reversed(&image.into_raw(), image_dimensions);
    let texture = glium::texture::Texture2d::with_mipmaps(
        display,
        image,
        MipmapsOption::AutoGeneratedMipmaps,
    )
    .unwrap();
    texture
}
